<a href="https://colab.research.google.com/github/shreyamsis2025-msis/ALA/blob/main/ProblemSet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install gensim

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 5.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 46.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 21.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 34.6 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.16.1
    Uninstalling scipy-1.16.1:
      Successfully uninstalled scipy-1.16.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatibl

In [ ]:
import numpy as np
import torch
import matplotlib.pyplot as plt
plt.style.use('dark_background')
%matplotlib inline
import sys
from sklearn.preprocessing import StandardScaler, OneHotEncoder, MinMaxScaler
import nltk
import gensim.downloader
from nltk.tokenize import word_tokenize

In [ ]:
# 1st question
v1 = torch.tensor([1,2,3],dtype=torch.float64)
v2 = torch.tensor([1,1,1],dtype=torch.float64)

#a
print(torch.sqrt(torch.dot(v1,v1)))
print(torch.sqrt(torch.dot(v2,v2)))

print((torch.sqrt(torch.dot(v1,v1)/3)))
print((torch.sqrt(torch.dot(v2,v2)/3)))

#b
v1_mc = v1 - torch.mean(v1)
v2_mc = v2 - torch.mean(v2)
print(v1_mc)
print(v2_mc)

#c
print(torch.mean(v1_mc))
print(torch.mean(v2_mc))

#d
std_v1 = torch.sqrt(torch.mean(v1_mc**2))
std_v2 = torch.sqrt(torch.mean(v2_mc**2))
print(std_v1)
print(std_v2)

#e
#Refer practise

#f
print(v1_mc/std_v1)
print(v2_mc/std_v2)

tensor(3.7417, dtype=torch.float64)
tensor(1.7321, dtype=torch.float64)
tensor(2.1602, dtype=torch.float64)
tensor(1., dtype=torch.float64)
tensor([-1.,  0.,  1.], dtype=torch.float64)
tensor([0., 0., 0.], dtype=torch.float64)
tensor(0., dtype=torch.float64)
tensor(0., dtype=torch.float64)
tensor(0.8165, dtype=torch.float64)
tensor(0., dtype=torch.float64)
tensor([-1.2247,  0.0000,  1.2247], dtype=torch.float64)
tensor([nan, nan, nan], dtype=torch.float64)


In [ ]:
# 2nd Question
a = torch.tensor([0.0, -1.0, -2.0])
b = torch.tensor([0.0,  1.0,  2.0])
print(a)
print(b)

rms = torch.sqrt(((a[1])**2 + (a[1])**2 + (a[1])**2 )/3)
print(rms)

print(torch.mean(a))
print(torch.mean(b))
print(torch.mean(-3 * b))

a_mc = a - torch.mean(a)
v = torch.mean(a_mc**2)
s = torch.sqrt(v)
print(f'Standard Deviation: {s}')

print(f'Standard Deviation -3a: { -3 * s}')

corr = np.corrcoef(a,b)
print(corr)

print(torch.norm(a - b))

print((180.0/torch.pi)*(torch.acos(torch.dot(a,b) / (torch.norm(a) * torch.norm(b)))))

tensor([ 0., -1., -2.])
tensor([0., 1., 2.])
tensor(1.)
tensor(-1.)
tensor(1.)
tensor(-3.)
Standard Deviation: 0.8164966106414795
Standard Deviation -3a: -2.4494898319244385
[[ 1. -1.]
 [-1.  1.]]
tensor(4.4721)
tensor(180.)


In [ ]:
#Practise
c = torch.tensor([1,2,3,4],dtype=torch.float64)
d = 2 * c
c_mc = c - torch.mean(c)
v_c = torch.mean(c_mc**2)
s_c = torch.sqrt(v_c)
print(f'Standard Deviation: {s_c}')

d_mc = d - torch.mean(d)
v_d = torch.mean(d_mc**2)
s_d = torch.sqrt(v_d)
print(f'Standard Deviation: {s_d}')

print(2*s_c)

Standard Deviation: 1.118033988749895
Standard Deviation: 2.23606797749979
tensor(2.2361, dtype=torch.float64)


3. Solved in class

    Investment-C or Investment-B is the best

In [ ]:
# 4th adjacency
A = torch.tensor([[0,1,1,0],
                  [1,0,0,1],
                  [0,0,0,1],
                  [1,0,0,0]
                  ],dtype=torch.float64)
e3 = torch.tensor([0,0,1,0],dtype=torch.float64)
print(torch.matmul(A,e3))
A

tensor([1., 0., 0., 0.], dtype=torch.float64)


tensor([[0., 1., 1., 0.],
        [1., 0., 0., 1.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.]], dtype=torch.float64)

In [ ]:
# 6th question
X = torch.tensor([1,1],dtype=torch.float64)
A = torch.tensor([[np.cos(180/4), -np.sin(180/4)],
                  [np.sin(180/4), np.cos(180/4)]],dtype=torch.float64)
B = torch.tensor([[4,0],
                 [0,4]],dtype=torch.float64)
print(A)
print(torch.matmul(A,X))
print(torch.matmul(B,X))

tensor([[ 0.5253, -0.8509],
        [ 0.8509,  0.5253]], dtype=torch.float64)
tensor([-0.3256,  1.3762], dtype=torch.float64)
tensor([4., 4.], dtype=torch.float64)


In [ ]:
# 7th question
A = torch.tensor([[0,0,0,0,1],
                  [1,0,0,0,0],
                  [0,1,0,0,0],
                  [0,0,1,0,0],
                  [0,0,0,1,0]])
x = torch.tensor([1,2,3,4,5])

print(torch.matmul(A,x))
a = torch.matmul(A,A)
c = torch.matmul(A,A)
d = torch.matmul(a,c)
e = torch.matmul(d,A)
print(e)



tensor([5, 1, 2, 3, 4])
tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])
